In [23]:
# Importing necessary libraries
import pandas as pd
from sklearn.feature_selection import SelectKBest, f_classif

In [2]:
# Loading the dataset
train_df = pd.read_csv("../data/raw/data_set_ALL_AML_train.csv")
test_df = pd.read_csv("../data/raw/data_set_ALL_AML_independent.csv")
labels_df = pd.read_csv("../data/raw/actual.csv")

In [3]:
# Inspecting the datasets
train_df.head()

,Gene Description,Gene Accession Number,1,call,2,call.1,3,call.2,4,call.3,...,29,call.33,30,call.34,31,call.35,32,call.36,33,call.37
0,AFFX-BioB-5_at (endogenous control),AFFX-BioB-5_at,-214,A,-139,A,-76,A,-135,A,...,15,A,-318,A,-32,A,-124,A,-135,A
1,AFFX-BioB-M_at (endogenous control),AFFX-BioB-M_at,-153,A,-73,A,-49,A,-114,A,...,-114,A,-192,A,-49,A,-79,A,-186,A
2,AFFX-BioB-3_at (endogenous control),AFFX-BioB-3_at,-58,A,-1,A,-307,A,265,A,...,2,A,-95,A,49,A,-37,A,-70,A
3,AFFX-BioC-5_at (endogenous control),AFFX-BioC-5_at,88,A,283,A,309,A,12,A,...,193,A,312,A,230,P,330,A,337,A
4,AFFX-BioC-3_at (endogenous control),AFFX-BioC-3_at,-295,A,-264,A,-376,A,-419,A,...,-51,A,-139,A,-367,A,-188,A,-407,A

In [4]:
test_df.head()

,Gene Description,Gene Accession Number,39,call,40,call.1,42,call.2,47,call.3,...,65,call.29,66,call.30,63,call.31,64,call.32,62,call.33
0,AFFX-BioB-5_at (endogenous control),AFFX-BioB-5_at,-342,A,-87,A,22,A,-243,A,...,-62,A,-58,A,-161,A,-48,A,-176,A
1,AFFX-BioB-M_at (endogenous control),AFFX-BioB-M_at,-200,A,-248,A,-153,A,-218,A,...,-198,A,-217,A,-215,A,-531,A,-284,A
2,AFFX-BioB-3_at (endogenous control),AFFX-BioB-3_at,41,A,262,A,17,A,-163,A,...,-5,A,63,A,-46,A,-124,A,-81,A
3,AFFX-BioC-5_at (endogenous control),AFFX-BioC-5_at,328,A,295,A,276,A,182,A,...,141,A,95,A,146,A,431,A,9,A
4,AFFX-BioC-3_at (endogenous control),AFFX-BioC-3_at,-224,A,-226,A,-211,A,-289,A,...,-256,A,-191,A,-172,A,-496,A,-294,A

In [5]:
# Transposing the data
train_df = train_df.set_index("Gene Description")
train_df = train_df.drop("Gene Accession Number", axis=1)

train_df = train_df.T
train_df.head()

Gene Description,AFFX-BioB-5_at (endogenous control),AFFX-BioB-M_at (endogenous control),AFFX-BioB-3_at (endogenous control),AFFX-BioC-5_at (endogenous control),AFFX-BioC-3_at (endogenous control),AFFX-BioDn-5_at (endogenous control),AFFX-BioDn-3_at (endogenous control),AFFX-CreX-5_at (endogenous control),AFFX-CreX-3_at (endogenous control),AFFX-BioB-5_st (endogenous control),...,Transcription factor Stat5b (stat5b) mRNA,Breast epithelial antigen BA46 mRNA,GB DEF = Calcium/calmodulin-dependent protein kinase II delta E mRNA; partial cds,TUBULIN ALPHA-4 CHAIN,CYP4B1 Cytochrome P450; subfamily IVB; polypeptide 1,PTGER3 Prostaglandin E receptor 3 (subtype EP3) {alternative products},HMG2 High-mobility group (nonhistone chromosomal) protein 2,RB1 Retinoblastoma 1 (including osteosarcoma),GB DEF = Glycophorin Sta (type A) exons 3 and 4; partial,GB DEF = mRNA (clone 1A7)
1,-214,-153,-58,88,-295,-558,199,-176,252,206,...,185,511,-125,389,-37,793,329,36,191,-37
call,A,A,A,A,A,A,A,A,A,A,...,A,A,A,P,A,A,A,A,A,A
2,-139,-73,-1,283,-264,-400,-330,-168,101,74,...,169,837,-36,442,-17,782,295,11,76,-14
call.1,A,A,A,A,A,A,A,A,A,A,...,A,A,A,A,A,A,A,A,A,A
3,-76,-49,-307,309,-376,-650,33,-367,206,-215,...,315,1199,33,168,52,1138,777,41,228,-41

In [6]:
# Checking the shape
print("Shape is : " , train_df.shape)

Shape is :  (76, 7129)

In [7]:
# Inspecting the labels
labels_df.head()

   patient cancer
0        1    ALL
1        2    ALL
2        3    ALL
3        4    ALL
4        5    ALL

### Data Cleaning and Label Integration

In [8]:
# Check column names
train_df.index[:5]

Index(['1', 'call', '2', 'call.1', '3'], dtype='object')

In [9]:
# Inspect the labels
labels_df.head()

   patient cancer
0        1    ALL
1        2    ALL
2        3    ALL
3        4    ALL
4        5    ALL

In [10]:
# Clean labels names
labels_df.columns = ["patient", "cancer"]

In [11]:
# Match index type
train_df.index = train_df.index.astype(str)
labels_df["patient"] = labels_df["patient"].astype(str)

In [12]:
# Merge labels with training data
df = train_df.merge(labels_df, left_index=True, right_on="patient")
df.head()

,AFFX-BioB-5_at (endogenous control),AFFX-BioB-M_at (endogenous control),AFFX-BioB-3_at (endogenous control),AFFX-BioC-5_at (endogenous control),AFFX-BioC-3_at (endogenous control),AFFX-BioDn-5_at (endogenous control),AFFX-BioDn-3_at (endogenous control),AFFX-CreX-5_at (endogenous control),AFFX-CreX-3_at (endogenous control),AFFX-BioB-5_st (endogenous control),...,GB DEF = Calcium/calmodulin-dependent protein kinase II delta E mRNA; partial cds,TUBULIN ALPHA-4 CHAIN,CYP4B1 Cytochrome P450; subfamily IVB; polypeptide 1,PTGER3 Prostaglandin E receptor 3 (subtype EP3) {alternative products},HMG2 High-mobility group (nonhistone chromosomal) protein 2,RB1 Retinoblastoma 1 (including osteosarcoma),GB DEF = Glycophorin Sta (type A) exons 3 and 4; partial,GB DEF = mRNA (clone 1A7),patient,cancer
0,-214,-153,-58,88,-295,-558,199,-176,252,206,...,-125,389,-37,793,329,36,191,-37,1,ALL
1,-139,-73,-1,283,-264,-400,-330,-168,101,74,...,-36,442,-17,782,295,11,76,-14,2,ALL
2,-76,-49,-307,309,-376,-650,33,-367,206,-215,...,33,168,52,1138,777,41,228,-41,3,ALL
3,-135,-114,265,12,-419,-585,158,-253,49,31,...,218,174,-110,627,170,-50,126,-91,4,ALL
4,-106,-125,-76,168,-230,-284,4,-122,70,252,...,57,504,-26,250,314,14,56,-25,5,ALL

In [13]:
# Drop unnecessary columns
df = df.drop("patient", axis=1)

In [14]:
# Check final shape
print("Final shape:", df.shape)

Final shape: (38, 7130)

In [15]:
# Encode labels
df["cancer"] = df["cancer"].map({
    "ALL": 0,
    "AML": 1
})

In [16]:
# Check final dataset
df.head()

,AFFX-BioB-5_at (endogenous control),AFFX-BioB-M_at (endogenous control),AFFX-BioB-3_at (endogenous control),AFFX-BioC-5_at (endogenous control),AFFX-BioC-3_at (endogenous control),AFFX-BioDn-5_at (endogenous control),AFFX-BioDn-3_at (endogenous control),AFFX-CreX-5_at (endogenous control),AFFX-CreX-3_at (endogenous control),AFFX-BioB-5_st (endogenous control),...,Breast epithelial antigen BA46 mRNA,GB DEF = Calcium/calmodulin-dependent protein kinase II delta E mRNA; partial cds,TUBULIN ALPHA-4 CHAIN,CYP4B1 Cytochrome P450; subfamily IVB; polypeptide 1,PTGER3 Prostaglandin E receptor 3 (subtype EP3) {alternative products},HMG2 High-mobility group (nonhistone chromosomal) protein 2,RB1 Retinoblastoma 1 (including osteosarcoma),GB DEF = Glycophorin Sta (type A) exons 3 and 4; partial,GB DEF = mRNA (clone 1A7),cancer
0,-214,-153,-58,88,-295,-558,199,-176,252,206,...,511,-125,389,-37,793,329,36,191,-37,0
1,-139,-73,-1,283,-264,-400,-330,-168,101,74,...,837,-36,442,-17,782,295,11,76,-14,0
2,-76,-49,-307,309,-376,-650,33,-367,206,-215,...,1199,33,168,52,1138,777,41,228,-41,0
3,-135,-114,265,12,-419,-585,158,-253,49,31,...,835,218,174,-110,627,170,-50,126,-91,0
4,-106,-125,-76,168,-230,-284,4,-122,70,252,...,649,57,504,-26,250,314,14,56,-25,0

### Data Cleaning and Quality Check

In [17]:
# Check for missing values
df.isnull().sum().sum()

np.int64(0)

In [18]:
# Exact location of missing values
df.isnull().sum().sort_values(ascending=False).head()

AFFX-BioB-5_at (endogenous control)    0
AFFX-BioB-M_at (endogenous control)    0
AFFX-BioB-3_at (endogenous control)    0
AFFX-BioC-5_at (endogenous control)    0
AFFX-BioC-3_at (endogenous control)    0
dtype: int64

### Observations
No missing values were found in the dataset.

In [19]:
# Check data types
df.dtypes.value_counts()

object    7129
int64        1
Name: count, dtype: int64

In [20]:
# Check for duplicates
df.duplicated().sum()

np.int64(0)

In [21]:
# Statistical Summary
df.describe().T

        count      mean       std  min  25%  50%  75%  max
cancer   38.0  0.289474  0.459606  0.0  0.0  0.0  1.0  1.0

### Data Quality Observations

The dataset contains a large number of gene expression features compared to the number of samples.

This high-dimensional structure is common in bioinformatics and may lead to challenges such as overfitting in machine learning models.

Data cleaning steps ensured that missing values and duplicates were handled appropriately.

### Feature Selection

In [22]:
# Seperate features and target variable
X = df.drop("cancer", axis=1)
y = df["cancer"]

In [25]:
# Selecting top features using statistical tests
selector = SelectKBest(score_func=f_classif, k=50) # Select top 50 features
X_new = selector.fit_transform(X, y)

selected_features = X.columns[selector.get_support()]
selected_features

Index(['PRKCD Protein kinase C; delta', 'ADM Adrenomedullin',
       'Liver mRNA for interferon-gamma inducing factor(IGIF)',
       'Nuclear Factor Nf-Il6',
       'INDUCED MYELOID LEUKEMIA CELL DIFFERENTIATION PROTEIN MCL1',
       'FTH1 Ferritin heavy chain', 'FTL Ferritin; light polypeptide',
       'LYN V-yes-1 Yamaguchi sarcoma viral related oncogene homolog',
       'PPGB Protective protein for beta-galactosidase (galactosialidosis)',
       'CD33 CD33 antigen (differentiation antigen)',
       'CST3 Cystatin C (amyloid angiopathy and cerebral hemorrhage)',
       'FAH Fumarylacetoacetate',
       'LGALS3 Lectin; galactoside-binding; soluble; 3 (galectin 3) (NOTE: redefinition of symbol)',
       'ATP6C Vacuolar H+ ATPase proton channel subunit',
       'CTSD Cathepsin D (lysosomal aspartyl protease)',
       'MAJOR HISTOCOMPATIBILITY COMPLEX ENHANCER-BINDING PROTEIN MAD3',
       'PEPTIDYL-PROLYL CIS-TRANS ISOMERASE; MITOCHONDRIAL PRECURSOR',
       'CDC25A Cell division cycle 25A', 'TRANSCRIPTION FACTOR RELB',
       'DF D component of complement (adipsin)', 'Azurocidin gene',
       'Thrombospondin-p50 gene extracted from Human thrombospondin-1 gene; partial cds',
       'Phosphotyrosine independent ligand p62 for the Lck SH2 domain mRNA',
       'Leukotriene C4 synthase (LTC4S) gene',
       'Lysophospholipase homolog (HU-K5) mRNA',
       'GB DEF = Homeodomain protein HoxA9 mRNA',
       'Catalase (EC 1.11.1.6) 5'flank and exon 1 mapping to chromosome 11; band p13 (and joined CDS)',
       'PRG1 Proteoglycan 1; secretory granule',
       'SPI1 Spleen focus forming virus (SFFV) proviral integration oncogene spi1',
       'ME491  gene extracted from H.sapiens gene for Me491/CD63 antigen',
       'Zyxin', 'LEPR Leptin receptor', 'GB DEF = CD36 gene exon 15',
       'C-myb gene extracted from Human (c-myb) gene; complete primary cds; and five complete alternatively spliced cds',
       'TIMP2 Tissue inhibitor of metalloproteinase 2',
       'APLP2 Amyloid beta (A4) precursor-like protein 2',
       'Interleukin 8 (IL8) gene', 'INTERLEUKIN-8 PRECURSOR',
       'EUKARYOTIC PEPTIDE CHAIN RELEASE FACTOR SUBUNIT 1',
       'ITGAX Integrin; alpha X (antigen CD11C (p150); alpha polypeptide)',
       'PFC Properdin P factor; complement', 'NF-IL6-beta protein mRNA',
       'CD36 CD36 antigen (collagen type I receptor; thrombospondin receptor)',
       'Epb72 gene exon 1', 'Metargidin precursor mRNA',
       'HOX 2.2 gene extracted from Human Hox2.2 gene for a homeobox protein',
       'LYZ Lysozyme', 'LYZ Lysozyme', 'Lysozyme gene (EC 3.2.1.17)',
       'RNS2 Ribonuclease 2 (eosinophil-derived neurotoxin; EDN)'],
      dtype='object')

In [26]:
# Create a new dataframe
X_selected = pd.DataFrame(X_new, columns=selected_features)
X_selected.head()

,PRKCD Protein kinase C; delta,ADM Adrenomedullin,Liver mRNA for interferon-gamma inducing factor(IGIF),Nuclear Factor Nf-Il6,INDUCED MYELOID LEUKEMIA CELL DIFFERENTIATION PROTEIN MCL1,FTH1 Ferritin heavy chain,FTL Ferritin; light polypeptide,LYN V-yes-1 Yamaguchi sarcoma viral related oncogene homolog,PPGB Protective protein for beta-galactosidase (galactosialidosis),CD33 CD33 antigen (differentiation antigen),...,PFC Properdin P factor; complement,NF-IL6-beta protein mRNA,CD36 CD36 antigen (collagen type I receptor; thrombospondin receptor),Epb72 gene exon 1,Metargidin precursor mRNA,HOX 2.2 gene extracted from Human Hox2.2 gene for a homeobox protein,LYZ Lysozyme,LYZ Lysozyme,Lysozyme gene (EC 3.2.1.17),RNS2 Ribonuclease 2 (eosinophil-derived neurotoxin; EDN)
0,-208,163,75,223,543,2654,5418,365,330,261,...,-70,-231,54,162,1057,424,921,382,557,174
1,334,176,129,1074,2972,6765,17348,624,811,101,...,364,322,209,169,785,368,4101,3606,2716,309
2,-386,133,44,148,485,3387,6156,108,212,309,...,-208,-452,128,-18,1147,717,2799,2997,1716,226
3,366,93,218,-53,740,1646,7070,873,584,288,...,34,-297,109,199,1210,537,1166,1331,1143,151
4,408,75,110,353,2453,2189,9017,686,1018,395,...,218,302,34,334,594,170,3250,3069,2917,672

In [27]:
# New shape
print("Shape of selected features:", X_selected.shape)

Shape of selected features: (38, 50)

### Feature Selection

Due to the high dimensionality of gene expression data, feature selection was applied to reduce the number of genes.

The top 50 genes were selected using a statistical test based on their relationship with the target variable.

This helps improve model performance and reduces overfitting.